     version: '3'
     services:
       frontend:
         build:
           context: ./src/frontend
           dockerfile: Dockerfile 
         ports:
           - "8080:8080"
       backend:
         build:
           context: ./src/backend
           dockerfile: Dockerfile 
         ports:
           - "8000:8000"