# Docker Compose configuration for GrowgrEbuddy_PSA
# This file defines the services for the frontend and backend applications.

version: '3.8'  # Specify the version of Docker Compose

services:
  frontend:
    build:
      context: ./src/frontend  # Build context for the frontend service
      dockerfile: Dockerfile  # Specify the Dockerfile to use
    ports:
      - "8081:8080"  # Map port 8081 on the host to port 8080 in the container
    depends_on:
      - backend  # Ensure the backend service is started before the frontend

  backend:
    build:
      context: ./src/backend  # Build context for the backend service
      dockerfile: Dockerfile  # Specify the Dockerfile to use
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 in the container
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings  # Set the Django settings module