name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js for the frontend
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Install frontend dependencies
    - name: Install frontend dependencies
      run: |
        cd src/frontend
        npm install

    # Run frontend tests
    - name: Run frontend tests
      run: |
        cd src/frontend
        npm run test

    # Set up Python for the backend
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Install backend dependencies
    - name: Install backend dependencies
      run: |
        cd src/backend
        pip install -r requirements.txt

    # Run backend tests
    - name: Run backend tests
      run: |
        cd src/backend
        python manage.py test

    # Optional: Build Docker images (if applicable)
    - name: Build Docker images
      run: |
        docker-compose build 